export const UPDATE_ROOM_NAME = 'UPDATE_ROOM_NAME';
export const UPDATE_QUEUE = 'UPDATE_QUEUE';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const UPDATE_ROOM_ID = 'UPDATE_ROOM_ID';
export const SET_ROOM_ERROR = 'SET_ROOM_ERROR';
